name: openapi2proto CI
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v5
      with:
        java-version: graalvm-ce-java11@20.0.0
    - name: Install native image
      run: gu install native-image
    - name: Compile and package bin
      run: sbt compile "graalvm-native-image:packageBin"
    - name: Save binary build openapi2proto
      uses: actions/upload-artifact@v2
      with:
        name: openapi2proto ${{ matrix.os }}
        path: target/graalvm-native-image/openapi2proto
