name: openapi2proto CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v5
      with:
        java-version: graalvm@
    - name: Install native image
      run: gu install native-image
    - name: Compile and package bin
      run: sbt compile "graalvm-native-image:packageBin"
