name: openapi2proto CI
on: [push]
jobs:
  build:
    runs-on: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v5
      with:
        java-version: graalvm@20.0.0
    - name: Install native image
      run: gu install native-image
    - name: Compile and package bin
      run: sbt compile "graalvm-native-image:packageBin"
    - name: Save binary build openapi2proto
      uses: actions/upload-artifact@v1
      with:
        name: openapi2proto
        path: target/graalvm-native-image/openapi2proto
